export function buildContractsSnapshot(config) {
  return {
    service: 'domain',
    responsibilities: [
      'sesiones-mesa',
      'comanda-compartida',
      'crud-categorias',
      'crud-subcategorias',
      'crud-productos',
      'abm-mesas',
      'plugins-operativos',
      'dashboard',
      'eventos-mqtt',
      'eventos-sse',
    ],
    httpContracts: {
      internalReadModels: [
        '/internal/bootstrap',
        '/internal/contracts',
        '/internal/catalog/contracts',
        '/internal/dashboard/contracts',
        '/internal/mobile/contracts',
        '/internal/public/bootstrap',
        '/internal/auth/session',
        '/internal/admin/dashboard',
        '/internal/admin/config',
        '/internal/admin/plugins/mesa-layout',
        '/internal/admin/categorias',
        '/internal/admin/subcategorias',
        '/internal/admin/productos',
        '/internal/admin/mesas',
        '/internal/waiter/queues',
        '/internal/waiter/consultas/:consultaId',
        '/internal/waiter/pedidos-cocina/:pedidoCocinaId',
        '/internal/waiter/llamados-mozo/:llamadoMozoId',
        '/internal/mobile/snapshot',
        '/internal/mobile/current/dashboard/metrics',
        '/internal/mobile/current/dashboard/revenue',
        '/internal/mobile/current/queues/:status/:queueType',
      ],
      internalCommands: [
        'POST /internal/auth/login',
        'POST /internal/auth/logout',
        'POST /internal/public/mesas/:mesaNumero/session',
        'POST /internal/public/mesas/:mesaNumero/connect',
        'POST /internal/public/mesas/:mesaNumero/disconnect',
        'POST /internal/public/mesas/:mesaNumero/comandas/items',
        'POST /internal/public/mesas/:mesaNumero/comandas/confirm',
        'POST /internal/public/mesas/:mesaNumero/waiter-call',
        'POST /internal/public/mesas/:mesaNumero/consulta/open',
        'POST /internal/public/mesas/:mesaNumero/consulta/message',
        'POST /internal/public/mesas/:mesaNumero/consulta/close',
        'PUT /internal/admin/config',
        'PUT /internal/admin/plugins/mesa-layout/enabled',
        'PUT /internal/admin/plugins/mesa-layout/layout',
        'POST /internal/admin/categorias',
        'PUT /internal/admin/categorias/:categoriaId',
        'DELETE /internal/admin/categorias/:categoriaId',
        'POST /internal/admin/productos',
        'PUT /internal/admin/productos/:productoId',
        'DELETE /internal/admin/productos/:productoId',
        'POST /internal/admin/mesas',
        'POST /internal/admin/mesas/:mesaNumero/open',
        'POST /internal/admin/mesas/:mesaNumero/close',
        'POST /internal/waiter/consultas/:consultaId/message',
        'POST /internal/waiter/consultas/:consultaId/close',
        'POST /internal/waiter/pedidos-cocina/:pedidoCocinaId/receive',
        'POST /internal/waiter/pedidos-cocina/:pedidoCocinaId/charge',
        'POST /internal/waiter/llamados-mozo/:llamadoMozoId/receive',
        'POST /internal/mobile/auth/manager-login',
        'POST /internal/mobile/history',
        'POST /internal/mobile/manager-web-session/close',
      ],
      realtime: [
        'GET /internal/events/stream (SSE)',
      ],
    },
    mqttContracts: {
      baseTopic: config.mqttBaseTopic,
      topics: {
        androidInboundLoginRequest: `${config.mqttBaseTopic}/android/in/auth/login/request`,
        androidInboundHistoryRequest: `${config.mqttBaseTopic}/android/in/history/request`,
        androidInboundCloseWebSessionRequest: `${config.mqttBaseTopic}/android/in/system/web-session/close/request`,
        androidInboundWebEntrypointRequest: `${config.mqttBaseTopic}/android/in/system/web-entrypoint/request`,
        androidOutboundLoginResponse: `${config.mqttBaseTopic}/android/out/{deviceId}/auth/login/response`,
        androidOutboundCurrentDashboardMetrics: `${config.mqttBaseTopic}/android/out/{deviceId}/current/dashboard/metrics`,
        androidOutboundCurrentDashboardRevenue: `${config.mqttBaseTopic}/android/out/{deviceId}/current/dashboard/revenue`,
        androidOutboundCurrentQueues: `${config.mqttBaseTopic}/android/out/{deviceId}/current/queue/{statusBucket}/{queueType}`,
        androidOutboundHistoryFragments: `${config.mqttBaseTopic}/android/out/{deviceId}/history/{requestId}/#`,
        androidOutboundWebEntrypointCurrent: `${config.mqttBaseTopic}/android/out/{deviceId}/system/web-entrypoint/current`,
        androidOutboundSystemEvents: `${config.mqttBaseTopic}/android/out/{deviceId}/system/#`,
      },
      payloads: {
        loginRequest: ['requestId', 'deviceId', 'username', 'password'],
        loginResponse: ['requestId', 'accepted', 'reason', 'deviceId'],
        currentDashboardMetrics: ['generatedAt', 'scope', 'fromUtc', 'toUtc', 'metrics'],
        currentDashboardRevenue: ['generatedAt', 'scope', 'fromUtc', 'toUtc', 'items'],
        currentQueueFragment: ['generatedAt', 'scope', 'fromUtc', 'toUtc', 'status', 'queueType', 'items'],
        historyRequest: ['requestId', 'deviceId', 'fromUtc', 'toUtc'],
        historyFragment: ['requestId', 'generatedAt', 'scope', 'fromUtc', 'toUtc'],
        systemEvent: ['type', 'deviceId', 'generatedAt', 'reason'],
      },
    },
  };
}
